import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class BeritaserviceService {

  constructor() { }
  getNews = function(){
    return [
      {"id": "1", "judul" : "Makanan Terenak di Dunia, Rendang.", "isi" : "Rendang, Indonesia Makanan terenak di Dunia yang pertama adalah Rendang, rendang masuk sebagai salah satu makanan terenak hingga kelas dunia. Makanan yang satu ini patut untuk dibanggakan oleh masyarakat indonesia karena banyak dari masyarakat luar negeri yang mengakui kenikmatannya.Rendang merupakan makanan yang terbuat dari bahan dasar daging sapi yang dimasak lama dengan rempah istimewa sehingga hasilnya empuk dan bumbunya sangat merasa. Masyarakat indonesia bisa menjadikan makanan ini sebagai menu istimewa meskipun asal dari padang. Bagi warga bali, makanan khas bali berupa bebek betutu adalah makanan ternikmat di daerahnya, karena disana makanan ini menjadi terfavorit dan paling dicari oleh para wisatawan."},
      {"id": '2', 'judul' : 'Makanan Terenak di Dunia, Nasi Goreng', 'isi' : "Makanan selanjutnya yang juag masuk sebagai salah satu makanan yang terenak di dunia masih berasal dari indonesia yakni nasi goreng. Masyarakat indonesia tentu saja sudah sangat kenal dengan makanan yang satu ini. Saking enaknya, nasi goreng sangat mudah ditemukan karena banyak dijual di banyak wilayah di indonesia. Nasi goreng memang telah diakui oleh penikmatnya memiliki rasa yang gurih dan nikmat apalagi ada tambahan daging yang dan telor. Anda tentu juga akan sangat setuju jika nasi goreng masuk sebagai makanan terenak bukan hanya di indonesia melainkan di dunia."},
      {"id": '3', 'judul' : '4 Bintang Plus Ronaldo Disebut Tak Bahagia Dilatih Solskjaer', 'isi' : "Jakarta, CNN Indonesia -- Cristiano Ronaldo dan empat pemain bintang Manchester United diklaim sudah tak bahagia dilatih Ole Gunnar Solskjaer.Hasil imbang 1-1 yang diraih Man Utd saat menjamu Everton pada lanjutan Liga Inggris di Stadion Old Trafford membuat para pemain gerah. Solskjaer dianggap sebagai biang keladinya.Setan Merah hanya mampu memenangkan dua dari lima pertandingan terakhir mereka di semua kompetisi. Hasil negatif ini membuat Solskjaer jadi sasaran kritik pedas atas inkonsistensi klub. Sport Bible melaporkan, Ronaldo dan Paul Pogba masuk daftar pemain bintang yang tak bahagia dilatih Solskjaer menyusul hasil imbang melawan Everton.Kiper Man Utd David de Gea juga diklaim sangat marah dengan hasil imbang di Old Trafford dan meluapkan kekecewaannya kepada rekan setim. Jadon Sancho yang tengah berjuang memberikan dampak besar di United juga dilaporkan kesal dengan keputusan Solskjaer yang menurunkannya di luar posisi sayap. Sancho sendiri terbiasa bermain di sektor sayap saat masih membela Borussia Dortmund.Pemain lain yang tak bahagia dengan kepemimpinan Solskjaer adalah Donny van de Beek. Gelandang asal Belanda tersebut sempat meluapkan kekecewaannya saat United menang 2-1 atas Villarreal di Liga Champions. Ronaldo dkk kini berada di posisi keempat klasemen sementara Liga Inggris dengan raihan 14 poin atau tertinggal dua angka dari Chelsea yang berhak menduduki posisi puncak.Sebagian besar penggawa Man Utd bakal membela negaranya masing-masing di kalander internasional sebelum melawat ke markas Leicester City pada lanjutan Liga Inggris, Sabtu (16/10). Lima hari berselang, Red Devils akan menjamu Atalanta di Liga Champions."},
      {"id": '4', 'judul' : 'Beredar Rumor Jisoo BLACKPINK Ditelantarkan YG Entertainment, CEO Dior Siap Rekrut', 'isi' : "Kehadiran Jisoo BLACKPINK di Paris Fashion Week dalam presentasi Dior mendapat sorotan. Tak hanya sebagai brand ambassador saja, namun rumor yang beredar jika CEO Dior, Pietro Beccari membuat pernyataan jika siap menampun Jisoo jika ditelantarkan YG, agensi yang menaungi BLACKPINK.Berita ini viral kala Elle Taiwan mengabadikan momen ketika Jisoo BLACKPINK dan CEO Dior tengah berbincang akrab. Perbincangan santai tersebut disadari oleh salah satu penggemar, yang akhirnya tersebar luas. Video tersebut terlihat saat CEO Dior DIOR menghampiri staf management YG Entertainment dan berkata jika 'If YG fires her, message me. I'll take her' yang berarti 'Bila YG memecatnya, hubungi aku, aku akan merekrutnya'."},
      {"id": '5', 'judul' : 'Mark Zuckerberg Kehilangan Rp85,6 T karena WhatsApp, Instagram, Facebook Down 6 Jam', 'isi' : "Pemilik Facebook, Instagram, dan Whatsapp Mark Zuckerberg kehilangan harta sebesar 6 miliar dollar AS atau sekitar Rp85,6 triliun (asumsi kurs Rp14.300) dalam hitungan jam. Penyebabnya, harga saham Facebook anjlok imbas layanan 3 aplikasi tersebut yang down sejak Senin (4/10/2021) malam. Mengutip Bloomberg, Selasa (5/10/2021), saham Facebook turun 5 persen pada perdagangan Senin waktu setempat dibanding pada penutupan perdagangan Jumat pekan lalu. Harga saham Facebook bahkan turun 15 persen dibanding pertengahan September.Alhasil, kekayaan Zuckerberg yang mayoritas berasal dari saham Facebook juga ambles miliaran dollar. Bloomberg menaksir harga Zuckerberg saat ini menjadi 121,6 miliar dollar AS. Hal itu membuat Zuckerberg merosot ke posisi 5 dalam Bloomberg Billionaires Index, yang merupakan peringkat 500 orang terkaya di dunia. Persis di atasnya, ada pendiri Microsoft Bill Gates di peringkat 4 dengan kekayaan bersih 124 miliar dollar AS. Layanan Facebook, Instagram, dan Whatsapp down sejak Senin pukul 23.00 WIB. Namun saat ini, layanan ketiganya telah kembali normal. Zuckerberg juga sudah menyampaikan permohonan maafnya kepada publik lewat akun Facebooknya. 'Facebook, Instagram, WhatsApp, dan Messenger kini kembali online. Maaf atas gangguan hari ini -- Saya tahu betapa Anda mengandalkan layanan kami untuk tetap terhubung dengan orang-orang yang Anda sayangi,' tulis Zuckerberg. Facebook, Instagram, dan Whatsapp down selama 6 jam. Para penggunanya pun beralih ke akun sosmed mereka yang lain, seperti Twitter. Mereka juga mengeluhkan layanan 3 platform tersebut yang tidak bisa diakses. Pihak Facebook kini tengah menyelidiki penyebab kejadian tersebut."}
    ]
  }

  getBlogs = function(){
    return [
      { "id": "1", "judul": "Manfaat Teh Hijau", "isi" : "Teh hijau baik untuk menurunkan kadar kolesterol. Hal ini karena kandungan polifenol dalam teh hijau kemungkinan mampu menghalangi kolesterol diserap usus sekaligus membantu menyingkirkannya, Kandungan polifenol dalam teh hijau memiliki peran dalam membantu membunuh sel kanker dan menghentikan pertumbuhan kanker. Mengonsumsi teh hijau secara rutin pada wanita disebut menurunkan risiko terkena kanker ovarium dan kanker endometrium. Teh hijau dapat meningkatkan kinerja insulin serta membantu mengurangi kadar gula darah pada penderita diabetes." },
      { "id": "2", "judul": "Manfaat Cabe Rawit", "isi" : "Cabe rawit merupakan salah satu tanaman yang termasuk kedalam jenis sayuran, tanaman ini sering digunakan untuk masakan agar masakan memiliki cita rasa yang beragam dengan keberadaannya cabai rawit tersebut. Rasa yang disumbangkan oleh manfaat cabe rawit merupakan rasa pedas, hal ini dikarenakan pada tumbuhan cabai rawit terdapat capsaicin yang menghasilkan rasa pedas pada tumbuhan ini. Pencernaan menjadi lebih lancar Bagi yang selalu mengalami permasalahan dengan urusan pencernaan, bisa dicoba untuk mengatasinya dengan mengkonsumsi cabai rawit ini. Memang sudah banyak beredar bahwa cabai rawit mampu membantu dalam proses melancarkan pencernaan, hal itu dikarenakan pada cabai rawit mampu menstimulasi sistem pencernaan dengan meningkatnya arus produksi enzim dan juga asam lambung. Oleh karena itu dapat membantu tubuh dalam proses terjadinya metabolisme makanan, lalu ketika sulit mengeluarkan gas dalam tubuh pun dapat diatasi dengan serbuk cabai karena serbuk cabe proses terjadinya asimilasi dan eliminasi dalam tubuh dengan adanya stimulasi gerakan peristaltic perut. Anti kanker, Kerja cabai rawit dalam masalah kanker ini yaitu dengan cara menghilangkan sel kanker yang ada dalam tubuh, tetapi proses ini tidak merusak sel normal yang ada pada tubuh. Kandungan yang ada dalam cabai rawit yang menangani penghilangan sel kanker adalah capsaicin, namun tidak dianjurkan pula dengan mengonsumsinya secara berlebihan." },
      { "id": "3", "judul": "Manfaat Timun", "isi" : "Salah satu dampak buruk dari terpapar radikal bebas adalah dapat menyebabkan stres oksidatif, yang dapat menyebabkan penyakit jantung, kanker, autoimun, dan penyakit paru-paru.Mentimun yang sangat kaya akan antioksidan bermanfaat untuk mengurangi kondisi tersebut. Antioksidan mentimun mengandung flavonoid dan tanin yang mana merupakan dua senyawa yang sangat efektif dalam memblokir radikal bebas yang berbahaya. Khasiat mentimun berikutnya adalah berpontesi membantu menurunkan berat badan, karena mentimun mengandung rendah kalori. Hal ini berarti kamu dapat mengonsumsi mentimun tanpa khawatir akan berdampak pada penambahan berat badan. Kamu bisa mengonsumsi dalam bentuk salad, sandwich, atau makanan pendamping pada beberapa menu makanan. Selain itu, kandungan air yang tinggi dapat membantu menurunkan berat badan yang signifikan. Meningkatkan imunitas tubuh. Seperti yang telah disebutkan sebelumnya, senyawa fitonutrien yang terkandung dalam madu dapat memperkuat sel-sel imun dalam tubuh. Hal ini tentunya akan memperkecil kemungkinan terjadinya penyakit infeksi. Ditambah lagi, madu juga diketahui memiliki khasiat sebagai antibakteri dan antijamur."  },
      { "id": "4", "judul": "Manfaat Madu","isi" : "Menangkal radikal bebas Senyawa fitonutrien dan sejumlah vitamin pada madu merupakan antioksidan alami yang dapat menangkal radikal bebas berlebih dalam tubuh. Khasiat madu ini sangat berguna untuk mencegah kerusakan sel dan jaringan tubuh yang disebabkan oleh aktivitas oksidasi.    Ada banyak manfaat yang bisa didapat dari kemampuan madu yang satu ini, di antaranya memperkuat sel imun tubuh, mencegah dan meredakan peradangan, mencegah reaksi alergi, serta mencegah diabetes, serangan jantung, hingga kanker. Meredakan batuk Rasa madu yang manis dapat memicu produksi air liur untuk melembapkan tenggorokan yang kering sehingga mengurangi rasa gatal di tenggorokan dan keinginan untuk batuk. Selain itu, berbagai antioksidan pada madu juga bermanfaat untuk meredakan peradangan yang bisa memicu batuk.  Khasiat madu sebagai obat batuk telah dibuktikan oleh banyak penelitian. Dari penelitian-penelitian tersebut disimpulkan bahwa madu bisa menjadi obat batuk alami yang tidak kalah dari obat batuk medis yang sering diresepkan dokter untuk orang dewasa, bahkan pada ibu menyusui, dan anak-anak berusia di atas 2 tahun."  },
      { "id": "5", "judul": "Manfaat Bawang Putih", "isi" : " Menurunkan Kolesterol Mengkonsumsi bawang putih mentah sebelum tidur dapat membantu mencegah kadar kolesterol yang tinggi dalam darah.  Hal tersebut berdasarkan jurnal penelitian yang pernah dipublikasikan oleh Journal of Postgraduate Medicine yang mengungkapkan bahwa mengkonsumsi sekitar 10 gram atau 1 sampai 2 siung bawang putih setiap hari berturut-turut selama sebulan dapat menurunkan kadar kolesterol secara signifikan.Selain itu penelitian lain juga membuktikan hal tersebut, yakni Pakistan Journal of Pharmaceutical Medicine yang menemukan manfaat makan bawang putih mentah bisa meningkatkan jumlah kolesterol HDL atau kolesterol baik dan menurunkan kadar kolesterol total dalam darah.  Menjaga Kesehatan JantungGrameds bisa menjaga kesehatan jantung dengan rutin mengkonsumsi bawang putih mentah. Karena bawang putih ampuh menurunkan kadar kolesterol jahat (LDL) sehingga dapat mencegah terbentuknya enzim pada organ hati yang biasanya menjadi penyebab kadar kolesterol dalam tubuh. Ternyata kandungan diallyl trisulfide dalam bawang putih juga dapat membantu melindungi jantung bagi orang yang pernah mengalami serangan jantung atau setelah bedah jantung dan orang yang pernah mengalami penanganan gagal jantung. Kemasyhuran manfaat bawang putih sebenarnya belum banyak penelitian yang membuktikannya dapat menjaga kesehatan jantung."  },
    ]
  }
}
